name: Cypress Tests

on:
  push:
    branches: ['*']
  workflow_dispatch:
  pull_request:
    branches: ['*']

jobs:
  test-2-0-4:
    name: Test v2.0.4 (Local)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup test environment
        run: |
          mkdir -p test-env
          cp -r @lottiefiles_lottie-player_2.0.4/* test-env/

      - name: Install dependencies
        working-directory: test-env
        run: |
          npm install --no-package-lock --legacy-peer-deps
          npm install cypress@9.2.1 @cypress/code-coverage --no-package-lock --legacy-peer-deps

      - name: Build and test
        working-directory: test-env
        run: |
          mkdir -p dist
          npm run build || true
          cp -r ../cypress .
          node cypress/pages/server.js &
          sleep 5
          npx cypress run --spec "cypress/integration/lottie-player/load_animation.spec.js"

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: results-2.0.4
          path: test-env/cypress/screenshots

  test-2-0-5:
    name: Test v2.0.5 (Local)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup test environment
        run: |
          mkdir -p test-env
          cp -r @lottiefiles_lottie-player_2.0.5/* test-env/

      - name: Install dependencies
        working-directory: test-env
        run: |
          npm install --no-package-lock --legacy-peer-deps
          npm install cypress@9.2.1 @cypress/code-coverage --no-package-lock --legacy-peer-deps

      - name: Build and test
        working-directory: test-env
        run: |
          mkdir -p dist
          npm run build || true
          cp -r ../cypress .
          node cypress/pages/server.js &
          sleep 5
          npx cypress run --spec "cypress/integration/lottie-player/load_animation.spec.js"

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: results-2.0.5
          path: test-env/cypress/screenshots

  test-2-0-8:
    name: Test v2.0.8 (Registry)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup test environment
        run: |
          mkdir -p test-env
          cd test-env
          npm init -y
          npm install @lottiefiles/lottie-player@2.0.8 --save-exact
          cp -r node_modules/@lottiefiles/lottie-player/* .

      - name: Install dependencies
        working-directory: test-env
        run: |
          npm install --no-package-lock --legacy-peer-deps
          npm install cypress@9.2.1 @cypress/code-coverage --no-package-lock --legacy-peer-deps

      - name: Build and test
        working-directory: test-env
        run: |
          mkdir -p dist
          npm run build || true
          cp -r ../cypress .
          node cypress/pages/server.js &
          sleep 5
          npx cypress run --spec "cypress/integration/lottie-player/load_animation.spec.js"

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: results-2.0.8
          path: test-env/cypress/screenshots

  generate-report:
    needs: [test-2-0-4, test-2-0-5, test-2-0-8]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Generate comparison report
        run: |
          echo "# Lottie Player Version Test Results" > report.md
          echo "Generated: $(date)" >> report.md
          echo "" >> report.md
          
          echo "## Version 2.0.4 (Local)" >> report.md
          if [ -d "artifacts/results-2.0.4" ]; then
            echo "✅ Tests completed" >> report.md
            ls -la artifacts/results-2.0.4 >> report.md
          else
            echo "❌ Tests failed or not completed" >> report.md
          fi
          echo "" >> report.md
          
          echo "## Version 2.0.5 (Local)" >> report.md
          if [ -d "artifacts/results-2.0.5" ]; then
            echo "✅ Tests completed" >> report.md
            ls -la artifacts/results-2.0.5 >> report.md
          else
            echo "❌ Tests failed or not completed" >> report.md
          fi
          echo "" >> report.md
          
          echo "## Version 2.0.8 (Registry)" >> report.md
          if [ -d "artifacts/results-2.0.8" ]; then
            echo "✅ Tests completed" >> report.md
            ls -la artifacts/results-2.0.8 >> report.md
          else
            echo "❌ Tests failed or not completed" >> report.md
          fi

      - name: Upload final report
        uses: actions/upload-artifact@v3
        with:
          name: version-comparison-report
          path: report.md
