name: Release

on:
  push:
    branches: [master]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache NPM
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean npm config and update package.json
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          # Update package.json to fix dependency issues
          jq '
            del(.dependencies["@lottiefiles/eslint-plugin"]) |
            .devDependencies["rollup"] = "^1.32.1" |
            .devDependencies["@types/node"] = "^14.x" |
            .devDependencies["webpack"] = "^5.x" |
            .devDependencies["babel-loader"] = "^9.x" |
            del(.devDependencies["rollup-plugin-terser"]) |
            .devDependencies["@rollup/plugin-terser"] = "^0.4.0"
          ' package.json > temp.json && mv temp.json package.json
      - name: Install global dependencies
        run: |
          npm install -g shx
          npm install -g typescript
          npm install -g rollup
      - uses: listendev/action@v0.11.0
        with:
          ci: 'only'
          jwt: ${{ secrets.LSTN_API_KEY }}
          lstn: 'v0.15.0'
      - name: Install dependencies
        run: |
          yarn install --no-lockfile --ignore-optional --network-timeout 100000 --legacy-peer-deps
          npm install --no-package-lock --legacy-peer-deps
        continue-on-error: true
      - name: Create dist directory
        run: |
          mkdir -p dist
      - name: Generate versions file
        run: |
          echo "export const LOTTIE_PLAYER_VERSION = '0.0.1';" > src/versions.ts
          echo "export const LOTTIE_WEB_VERSION = '5.7.13';" >> src/versions.ts
      - name: Build project
        run: |
          npm run build --legacy-peer-deps || true
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - name: Pack and verify package
        run: |
          npm pack
          echo "Package contents that would be published:"
          tar -tzf *.tgz || true
          echo "Package would be published to npm registry (simulation only)"

  simulate-release:
    needs: build
    name: Simulate Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Clean npm config and update package.json
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          # Update package.json to fix dependency issues
          jq '
            del(.dependencies["@lottiefiles/eslint-plugin"]) |
            .devDependencies["rollup"] = "^1.32.1" |
            .devDependencies["@types/node"] = "^14.x" |
            .devDependencies["webpack"] = "^5.x" |
            .devDependencies["babel-loader"] = "^9.x" |
            del(.devDependencies["rollup-plugin-terser"]) |
            .devDependencies["@rollup/plugin-terser"] = "^0.4.0"
          ' package.json > temp.json && mv temp.json package.json
      - name: Install global dependencies
        run: |
          npm install -g shx
          npm install -g typescript
          npm install -g rollup
      - uses: listendev/action@v0.11.0
        with:
          ci: 'only'
          jwt: ${{ secrets.LSTN_API_KEY }}
          lstn: 'v0.15.0'
      - name: Install dependencies
        run: |
          yarn install --no-lockfile --ignore-optional --network-timeout 100000 --legacy-peer-deps
          npm install --no-package-lock --legacy-peer-deps
        continue-on-error: true
      - name: Create dist directory
        run: |
          mkdir -p dist
      - name: Generate versions file
        run: |
          echo "export const LOTTIE_PLAYER_VERSION = '0.0.1';" > src/versions.ts
          echo "export const LOTTIE_WEB_VERSION = '5.7.13';" >> src/versions.ts
      - name: Build project
        run: |
          npm run build --legacy-peer-deps || true
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - name: Pack and verify package
        run: |
          npm pack
          echo "Package contents that would be published:"
          tar -tzf *.tgz || true
          echo "Package would be published to npm registry (simulation only)"
