name: Release

on:
  push:
    branches: [master]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache NPM
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean npm config and remove private dependencies
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          # Remove @lottiefiles dependencies from package.json
          jq 'del(.dependencies["@lottiefiles/eslint-plugin"])' package.json > temp.json && mv temp.json package.json
          jq 'del(.devDependencies["@lottiefiles/eslint-plugin"])' package.json > temp.json && mv temp.json package.json
      - name: Install dependencies
        run: yarn install --no-lockfile --ignore-optional --network-timeout 100000
        continue-on-error: true
      - uses: listendev/action@v0.11.0
        with:
          ci: 'only'
          jwt: ${{ secrets.LSTN_API_KEY }}
          lstn: 'v0.15.0'
      - name: Build project
        run: yarn build
        continue-on-error: true
      - name: Run tests
        run: yarn test
        continue-on-error: true

  simulate-release:
    needs: build
    name: Simulate Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Clean npm config and remove private dependencies
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          # Remove @lottiefiles dependencies from package.json
          jq 'del(.dependencies["@lottiefiles/eslint-plugin"])' package.json > temp.json && mv temp.json package.json
          jq 'del(.devDependencies["@lottiefiles/eslint-plugin"])' package.json > temp.json && mv temp.json package.json
      - uses: listendev/action@v0.11.0
        with:
          ci: 'only'
          jwt: ${{ secrets.LSTN_API_KEY }}
          lstn: 'v0.15.0'
      - run: yarn install --no-lockfile --ignore-optional --network-timeout 100000
        continue-on-error: true
      - name: Build project
        run: yarn build
      - name: Pack and verify package
        run: |
          npm pack
          echo "Package contents that would be published:"
          tar -tzf *.tgz
          echo "Package would be published to npm registry (simulation only)"
          continue-on-error: true
